language: generic
dist: trusty
sudo: true
notifications:
  email:
    on_success: never
    on_failure: change

install:
  - pip install pipenv

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
